name: release
on:
  schedule:
    - cron: "* * * * *"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check and release
      run: |
        CORE_TAG_URL="https://api.github.com/repos/v2ray/v2ray-core/releases/latest"
        echo  $CORE_TAG_URL
        echo "${CORE_TAG_URL}"
        echo "${CORE_TAG_URL}"
        CORE_LATEST_VER=`(curl -sSL ${CORE_TAG_URL} --connect-timeout 30| grep 'tag_name' | cut -d\" -f4)`
        echo  $CORE_LATEST_VER
        echo "${CORE_LATEST_VER}"
        echo "${CORE_LATEST_VER}"
        if [[ ${CORE_LATEST_VER} != v* ]]; then
            CORE_LATEST_VER=v${CORE_LATEST_VER}
        fi
        DIST_TAGS_URL="https://api.github.com/repos/${{ github.repository }}/tags"
        echo  $DIST_TAGS_URL
        echo "${DIST_TAGS_URL}"
        echo "${DIST_TAGS_URL}"
        
        
        
        DIST_TAG_FOUND=`(curl -sSL ${DIST_TAGS_URL} --connect-timeout 30| grep "\"name\"\: \"${CORE_LATEST_VER}\"")` || true
        echo "${DIST_TAG_FOUND}"
        echo "${DIST_TAG_FOUND}"
        echo "${DIST_TAG_FOUND}"
        
        
        if [ -z ${DIST_TAG_FOUND} ]; then
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-dragonfly-64.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-freebsd-32.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-freebsd-64.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-32.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-64.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-arm.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-arm64.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-mips.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-mips64.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-mips64le.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-linux-s390x.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-macos.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-openbsd-32.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-openbsd-64.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-windows-32.zip > /dev/null
            wget https://github.com/v2ray/v2ray-core/releases/latest/download/v2ray-windows-64.zip > /dev/null
            wget https://github.com/${{ github.repository }}/raw/master/README.md
            mkdir -p .github/workflows
            wget -O .github/workflows/main.yml https://github.com/${{ github.repository }}/raw/master/.github/workflows/main.yml
            git init
            git add .
            git config user.name "Scaleya"
            git config user.email "61817665+Scaleya@users.noreply.github.com"
            git commit -m "Version ${CORE_LATEST_VER}"
            git tag -a "${CORE_LATEST_VER}" -m "Version ${CORE_LATEST_VER}"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push -u --force --follow-tags origin master
        fi
